//! Code generation from schema IR to Rust source files.
//!
//! Generates:
//! - `entities.rs`: Struct definitions with rmp-serde `Deserialize` impls
//!   using positional array format (`#[serde(deny_unknown_fields)]` on
//!   the tuple struct wrapper, with `rmp_serde::from_read` for array-based
//!   deserialization).
//! - `catalogs.rs`: `MasterDataCatalogs` struct with 29 table fields + accessors.
//! - `enums.rs`: Named enum types with `TryFrom<i32>`.

use std::fmt::Write;

use super::parser::SchemaIr;

/// Generate the `entities.rs` source file.
pub fn generate_entities(ir: &SchemaIr) -> String {
    let mut out = String::new();

    // Header
    writeln!(out, "// Auto-generated by blackbox-master-data/codegen. DO NOT EDIT.").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "use serde::{{Deserialize, Serialize}};").unwrap();
    writeln!(out).unwrap();

    for table in &ir.tables {
        let struct_name = sanitize_struct_name(&table.struct_name);
        writeln!(out, "/// Table `{}`.", table.key).unwrap();
        writeln!(out, "#[derive(Debug, Clone, Serialize)]").unwrap();
        writeln!(out, "pub struct {} {{", struct_name).unwrap();

        for col in &table.columns {
            let field = sanitize_field_name(&col.field_name);
            let ty = col.rust_type.as_rust_type();
            writeln!(out, "    pub {}: {},", field, ty).unwrap();
        }

        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();

        // Generate Deserialize impl using positional array format
        writeln!(out, "impl<'de> Deserialize<'de> for {} {{", struct_name).unwrap();
        writeln!(out, "    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>").unwrap();
        writeln!(out, "    where").unwrap();
        writeln!(out, "        D: serde::Deserializer<'de>,").unwrap();
        writeln!(out, "    {{").unwrap();
        writeln!(out, "        struct FieldVisitor;").unwrap();
        writeln!(out).unwrap();
        writeln!(out, "        impl<'de> serde::de::Visitor<'de> for FieldVisitor {{").unwrap();
        writeln!(out, "            type Value = {};", struct_name).unwrap();
        writeln!(out).unwrap();
        writeln!(out, "            fn expecting(&self, formatter: &mut std::fmt::Formatter) -> std::fmt::Result {{").unwrap();
        writeln!(out, "                formatter.write_str(\"a positional array with {} elements\")", table.columns.len()).unwrap();
        writeln!(out, "            }}").unwrap();
        writeln!(out).unwrap();

        // Use seq_access for positional deserialization
        writeln!(out, "            fn visit_seq<A>(self, mut seq: A) -> Result<Self::Value, A::Error>").unwrap();
        writeln!(out, "            where").unwrap();
        writeln!(out, "                A: serde::de::SeqAccess<'de>,").unwrap();
        writeln!(out, "            {{").unwrap();

        for (i, col) in table.columns.iter().enumerate() {
            let field = sanitize_field_name(&col.field_name);
            let ty = col.rust_type.as_rust_type();
            writeln!(out, "                let {}: {} = seq.next_element()?.ok_or_else(|| serde::de::Error::invalid_length({}, &self))?;", field, ty, i).unwrap();
        }

        writeln!(out, "                Ok({} {{", struct_name).unwrap();
        for col in &table.columns {
            let field = sanitize_field_name(&col.field_name);
            writeln!(out, "                    {},", field).unwrap();
        }
        writeln!(out, "                }})").unwrap();
        writeln!(out, "            }}").unwrap();
        writeln!(out, "        }}").unwrap();
        writeln!(out).unwrap();
        writeln!(out, "        deserializer.deserialize_tuple({}, FieldVisitor)", table.columns.len()).unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }

    out
}

/// Generate the `catalogs.rs` source file.
pub fn generate_catalogs(ir: &SchemaIr) -> String {
    let mut out = String::new();

    writeln!(out, "// Auto-generated by blackbox-master-data/codegen. DO NOT EDIT.").unwrap();
    writeln!(out).unwrap();
    writeln!(out).unwrap();

    // MasterDataCatalogs struct
    writeln!(out, "/// Holds all master data tables, keyed by table name.").unwrap();
    writeln!(out, "#[derive(Debug, Clone, Default)]").unwrap();
    writeln!(out, "pub struct MasterDataCatalogs {{").unwrap();

    for table in &ir.tables {
        let struct_name = sanitize_struct_name(&table.struct_name);
        let field_name = snake_case(&table.key);
        writeln!(out, "    pub {}: HashMap<i32, entities::{}>,", field_name, struct_name).unwrap();
    }

    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // Accessor methods
    writeln!(out, "impl MasterDataCatalogs {{").unwrap();
    for table in &ir.tables {
        let struct_name = sanitize_struct_name(&table.struct_name);
        let field_name = snake_case(&table.key);
        let getter_name = format!("get_{}", field_name);

        writeln!(out, "    /// Get an entity from table `{}` by its primary key.", table.key).unwrap();
        writeln!(out, "    pub fn {}(&self, id: i32) -> Option<&entities::{}> {{", getter_name, struct_name).unwrap();
        writeln!(out, "        self.{}.get(&id)", field_name).unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out).unwrap();
    }
    writeln!(out, "}}").unwrap();

    out
}

/// Generate the `enums.rs` source file.
pub fn generate_enums(ir: &SchemaIr) -> String {
    let mut out = String::new();

    writeln!(out, "// Auto-generated by blackbox-master-data/codegen. DO NOT EDIT.").unwrap();
    writeln!(out).unwrap();

    for enum_name in &ir.enums {
        let name = sanitize_enum_name(enum_name);
        writeln!(out, "/// Enum type `{}`.", enum_name).unwrap();
        writeln!(out, "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]").unwrap();
        writeln!(out, "pub enum {} {{", name).unwrap();
        writeln!(out, "    Unknown(i32) = -1,").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();

        writeln!(out, "impl TryFrom<i32> for {} {{", name).unwrap();
        writeln!(out, "    type Error = i32;").unwrap();
        writeln!(out).unwrap();
        writeln!(out, "    fn try_from(value: i32) -> Result<Self, Self::Error> {{").unwrap();
        writeln!(out, "        if value < 0 {{").unwrap();
        writeln!(out, "            Ok({}::Unknown(value))", name).unwrap();
        writeln!(out, "        }} else {{").unwrap();
        writeln!(out, "            Err(value)").unwrap();
        writeln!(out, "        }}").unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }

    out
}

// ── Helpers ────────────────────────────────────────────────────────────────

/// Convert a schema class name to a valid Rust struct name.
fn sanitize_struct_name(name: &str) -> String {
    // Go format: "EntityMAbility" → keep as-is (valid Rust)
    // Handle leading underscore (Go convention for unused fields)
    let mut result = String::with_capacity(name.len());
    let mut chars = name.chars().peekable();

    if chars.peek() == Some(&'_') {
        result.push(chars.next().unwrap());
    }

    let mut prev_underscore = false;
    for c in chars {
        if c == '_' {
            if !prev_underscore {
                result.push('_');
            }
            prev_underscore = true;
        } else {
            result.push(c);
            prev_underscore = false;
        }
    }

    // Ensure it doesn't start with a digit
    if result.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        result.insert(0, '_');
    }

    result
}

/// Convert a field name to Rust snake_case.
fn sanitize_field_name(name: &str) -> String {
    // Go uses PascalCase for fields: "AbilityId" → "ability_id"
    let mut result = String::with_capacity(name.len());
    for (i, c) in name.chars().enumerate() {
        if c.is_ascii_uppercase() {
            if i > 0 {
                result.push('_');
            }
            result.push(c.to_ascii_lowercase());
        } else {
            result.push(c);
        }
    }
    result
}

/// Convert an enum type name to Rust PascalCase.
fn sanitize_enum_name(name: &str) -> String {
    // Already PascalCase in schema, just validate
    let mut result = String::with_capacity(name.len());
    let mut chars = name.chars();
    if let Some(c) = chars.next() {
        result.push(c);
    }
    result.extend(chars);
    result
}

/// Convert a table key to snake_case field name.
fn snake_case(key: &str) -> String {
    // "m_ability" → "m_ability" (already snake_case)
    // "m_actor_animation" → "m_actor_animation"
    key.to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use super::super::parser::*;

    fn make_test_ir() -> SchemaIr {
        SchemaIr {
            tables: vec![
                ParsedTable {
                    key: "m_ability".into(),
                    struct_name: "EntityMAbility".into(),
                    columns: vec![
                        ParsedColumn { position: 0, field_name: "AbilityId".into(), rust_type: RustType::I32 },
                        ParsedColumn { position: 1, field_name: "AbilityLevelGroupId".into(), rust_type: RustType::I32 },
                    ],
                },
                ParsedTable {
                    key: "m_actor".into(),
                    struct_name: "EntityMActor".into(),
                    columns: vec![
                        ParsedColumn { position: 0, field_name: "ActorId".into(), rust_type: RustType::I32 },
                        ParsedColumn { position: 1, field_name: "ActorAssetId".into(), rust_type: RustType::String },
                        ParsedColumn { position: 2, field_name: "IsDefault".into(), rust_type: RustType::Bool },
                    ],
                },
            ],
            enums: vec!["AbilityBehaviourType".into(), "AttributeType".into()],
        }
    }

    #[test]
    fn generate_entities_output() {
        let ir = make_test_ir();
        let output = generate_entities(&ir);
        assert!(output.contains("pub struct EntityMAbility"));
        assert!(output.contains("pub ability_id: i32"));
        assert!(output.contains("pub ability_level_group_id: i32"));
        assert!(output.contains("pub struct EntityMActor"));
        assert!(output.contains("pub actor_id: i32"));
        assert!(output.contains("pub is_default: bool"));
        assert!(output.contains("pub actor_asset_id: String"));
        assert!(output.contains("impl<'de> Deserialize<'de> for EntityMAbility"));
    }

    #[test]
    fn generate_catalogs_output() {
        let ir = make_test_ir();
        let output = generate_catalogs(&ir);
        assert!(output.contains("pub struct MasterDataCatalogs"));
        assert!(output.contains("pub m_ability: HashMap<i32, entities::EntityMAbility>"));
        assert!(output.contains("pub fn get_m_ability"));
    }

    #[test]
    fn generate_enums_output() {
        let ir = make_test_ir();
        let output = generate_enums(&ir);
        assert!(output.contains("pub enum AbilityBehaviourType"));
        assert!(output.contains("impl TryFrom<i32> for AbilityBehaviourType"));
    }

    #[test]
    fn sanitize_field_name() {
        assert_eq!(sanitize_field_name_str("AbilityId"), "ability_id");
        assert_eq!(sanitize_field_name_str("ActorAssetId"), "actor_asset_id");
        assert_eq!(sanitize_field_name_str("IsDefault"), "is_default");
        assert_eq!(sanitize_field_name_str("QuestId"), "quest_id");
    }
}
