use std::env;
use std::path::PathBuf;

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let schemas_path = PathBuf::from("schemas.json");

    if schemas_path.exists() {
        // Parse schemas.json and generate Rust code
        let content = std::fs::read_to_string(&schemas_path).expect("Failed to read schemas.json");
        let schemas: serde_json::Value = serde_json::from_str(&content).expect("Invalid JSON");

        let mut code = String::new();
        code.push_str("// Auto-generated by build.rs — DO NOT EDIT\n\n");

        if let Some(obj) = schemas.as_object() {
            for (table_key, table_def) in obj {
                let class = table_def
                    .get("class")
                    .and_then(|c| c.as_str())
                    .unwrap_or("EntityUnknown");
                let columns = table_def.get("columns").and_then(|c| c.as_array());

                let mut fields = Vec::new();
                if let Some(cols) = columns {
                    for col in cols {
                        if let Some(arr) = col.as_array() {
                            if arr.len() >= 3 {
                                let name = arr[2].as_str().unwrap_or("unknown");
                                fields.push(format!("    pub {},", name));
                            }
                        }
                    }
                }

                code.push_str(&format!(
                    "#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]\npub struct {} {{\n{}\n}}\n\n",
                    class,
                    fields.join("\n")
                ));
            }
        }

        std::fs::write(out_dir.join("generated.rs"), code).expect("Failed to write generated code");
    } else {
        // Write placeholder so the crate compiles without schemas.json
        std::fs::write(
            out_dir.join("generated.rs"),
            "// Placeholder — schemas.json not found\n",
        )
        .expect("Failed to write generated code");
    }

    println!("cargo:rerun-if-changed=schemas.json");
}
